<?php

/**
 * @file
 * Contains specialfields.module.
 */

/**
 * Implements hook_form_alter().
 */
function prime_nodes_form_alter(&$form, $form_state, $form_id) {
  if ($form_id === "node_type_edit_form")
  {
    /* print_r($form_id); */
  }

  if (true)
    $form['#validate'][] = 'prime_nodes_date_form_validate';
}

function prime_nodes_date_form_validate($form, &$form_state) {
  /* if ($form_state['values']['date'] == 'test') { */
  /*   form_set_error('date', 'The creation day must be a prime number'); */
  /* } */
}
/**
 * Determine if input number is a prime number
 *
 * @param $n
 *   One number
 *
 * @return boolean
 *   The value representing whether or  not the input is a prime number.
 */
function isPrime($n) {
  for($x=2; $x<$n; $x++) {
    if($n %$x ==0) {
      return 0;
    }
  }
  return 1;
}
